[package]
name = "touch-rs"
version = "0.1.0"
authors = ["jacremer <jacremer@live.com>"]
edition = "2018"

[dependencies]
filetime = { git = "https://gitlab.redox-os.org/redox-os/filetime.git", branch = "redox" }
